### PR TITLE
Add module.exports for ESLint and JSHint rules

### PR DESCRIPTION
**Pull request by pdehaan**
This will make it easier to consume the configs using something like the following:

```js
var config = require('node-style-guide');

console.log(config.eslintrc);

/** OUTPUT:
{ env: { node: true },
  rules:
   { 'array-bracket-spacing': [ 2, 'never' ],
     'block-scoped-var': 2,
     'brace-style': [ 2, '1tbs' ],
     camelcase: 1,
     'computed-property-spacing': [ 2, 'never' ],
     curly: 2,
     'eol-last': 2,
     eqeqeq: [ 2, 'smart' ],
     'max-depth': [ 1, 3 ],
     'max-len': [ 1, 80 ],
     'max-statements': [ 1, 15 ],
     'new-cap': 1,
     'no-extend-native': 2,
     'no-mixed-spaces-and-tabs': 2,
     'no-trailing-spaces': 2,
     'no-unused-vars': 1,
     'no-use-before-define': [ 2, 'nofunc' ],
     'object-curly-spacing': [ 2, 'never' ],
     quotes: [ 2, 'single', 'avoid-escape' ],
     semi: [ 2, 'always' ],
     'space-after-keywords': [ 2, 'always' ],
     'space-unary-ops': 2 } }
*/
```

... Which also means I'll be able to update the **eslint-config-node-style-guide** module to do something as simple as:
```js
'use strict';
module.exports = require('node-style-guide').eslintrc;
```

### CODE REVIEW

**Comment by felixge** [comment]
LGTM

**Comment by pdehaan** [comment]
Merged, thanks.

Feel free to bump the version number and republish to npm at your convenience.

**Comment by felixge** [comment]
@pdehaan what's your npm username, so I can add you for doing it on your end?

**Comment by pdehaan** [comment]
@felixge https://www.npmjs.com/~pdehaan

**Comment by felixge** [comment]
hmm, it seems like there hasn't been a npm module publish for this yet, or am I missing something?

**Comment by pdehaan** [comment]
Odd, I thought you published it too, but it looks like you're correct!
In [eslint-config-node-style-guide](https://github.com/pdehaan/eslint-config-node-style-guide/blob/master/package.json#L11) I was just pulling it directly from your GitHub repo and then doing some hackery to load in the .eslintrc file within.

**Comment by felixge** [comment]
Published it and added you.

**Pull request merged**
