### PR TITLE
Created headers and reposition rules

### PR DESCRIPTION
**Pull request by GPHofficial**

### CODE REVIEW

**Comment by kentcdodds** [comment]
@felixge you might consider finding someone else to maintain this style guide. I'm afraid you can't count on me to give it much attention anymore :-(

**Comment by pdehaan** [comment]
@felixge @kentcdodds I can help, but I'll probably be a bit merge-happy on PRs and mostly be keeping the .eslintrc in sync with the latest changes.

**Comment by felixge** [comment]
@pdehaan added you as a contributor :). Feel free to merge stuff as you see fit. If I see something I don't like, I'll speak up. Thanks!

**Comment by pdehaan** [comment]
@felixge Thanks!

**Pull request merged**
